system:
  deployment: bootc
  arch: aarch64

logging:
  kind: basic
  level: debug

wanted:
  checks:
    - type: rootfs_readonly
required:
  checks:
    - type: unit_state
      unit: sshd.service
      expected: active
